language: node_js
sudo: false
node_js: 13
cache:
  directories:
    - "node_modules"
services:
  - docker

before_install: bash .travis/docker_setup_ssh.sh

before_script: npm run lint
after_success: bash .travis/docker_and_deploy.sh

email:
  on_failure: change
  on_success: never
